version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
  app:
    build: .
    command: python gui.py
    depends_on:
      - redis
      - grafana
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - GRAFANA_URL=http://grafana:3000
      - BOT_TOKEN=YOUR_BOT_TOKEN  # Substitua
      - SOURCE_SERVER=YOUR_SOURCE_SERVER_ID  # Substitua (modo Bot)
      - DEST_SERVER=YOUR_DEST_SERVER_ID  # Substitua
  worker:
    build: .
    command: python worker.py
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - BOT_TOKEN=YOUR_BOT_TOKEN  # Substitua
      - SOURCE_SERVER=YOUR_SOURCE_SERVER_ID  # Substitua (modo Bot)
      - DEST_SERVER=YOUR_DEST_SERVER_ID  # Substitua
    deploy:
      replicas: 3